hide_download: true
hide_download_original: null
leftnav:
- identifier: fcd2d099-2c35-2bd4-9a54-5f99bbcd759c
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 702ebf5e-c035-a8df-f961-c9eb8aaa8b9d
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 9a668f60-c2e8-35d2-5c6c-b026dd6a5402
  name: Readings
  pageRef: /pages/readings/
  weight: 30
- identifier: aeddd55a-36bb-61f7-4c2d-5f6d5239cd80
  name: Additional Readings
  pageRef: /pages/readings/additional-readings
  parent: 9a668f60-c2e8-35d2-5c6c-b026dd6a5402
  weight: 40
- identifier: 68c0eccf-2d7e-ad19-e194-013c7db26c38
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
